# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import image_classification_pb2 as image__classification__pb2


class ImageClassificationStub(object):
    """The image classification service definition.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ClassifyImage = channel.unary_unary(
                '/imageclassification.ImageClassification/ClassifyImage',
                request_serializer=image__classification__pb2.ImageRequest.SerializeToString,
                response_deserializer=image__classification__pb2.ClassificationResponse.FromString,
                )
        self.HealthCheck = channel.unary_unary(
                '/imageclassification.ImageClassification/HealthCheck',
                request_serializer=image__classification__pb2.HealthCheckRequest.SerializeToString,
                response_deserializer=image__classification__pb2.HealthCheckResponse.FromString,
                )


class ImageClassificationServicer(object):
    """The image classification service definition.
    """

    def ClassifyImage(self, request, context):
        """Sends an image for classification
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """Performs health check
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ImageClassificationServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ClassifyImage': grpc.unary_unary_rpc_method_handler(
                    servicer.ClassifyImage,
                    request_deserializer=image__classification__pb2.ImageRequest.FromString,
                    response_serializer=image__classification__pb2.ClassificationResponse.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=image__classification__pb2.HealthCheckRequest.FromString,
                    response_serializer=image__classification__pb2.HealthCheckResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'imageclassification.ImageClassification', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ImageClassification(object):
    """The image classification service definition.
    """

    @staticmethod
    def ClassifyImage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/imageclassification.ImageClassification/ClassifyImage',
            image__classification__pb2.ImageRequest.SerializeToString,
            image__classification__pb2.ClassificationResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/imageclassification.ImageClassification/HealthCheck',
            image__classification__pb2.HealthCheckRequest.SerializeToString,
            image__classification__pb2.HealthCheckResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
