# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: image_classification.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1aimage_classification.proto\x12\x13imageclassification\"6\n\x0cImageRequest\x12\x12\n\nimage_path\x18\x01 \x01(\t\x12\x12\n\nimage_file\x18\x02 \x01(\x0c\"(\n\x16\x43lassificationResponse\x12\x0e\n\x06result\x18\x01 \x01(\t\"\x14\n\x12HealthCheckRequest\"%\n\x13HealthCheckResponse\x12\x0e\n\x06status\x18\x01 \x01(\t2\xdc\x01\n\x13ImageClassification\x12\x61\n\rClassifyImage\x12!.imageclassification.ImageRequest\x1a+.imageclassification.ClassificationResponse\"\x00\x12\x62\n\x0bHealthCheck\x12\'.imageclassification.HealthCheckRequest\x1a(.imageclassification.HealthCheckResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'image_classification_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_IMAGEREQUEST']._serialized_start=51
  _globals['_IMAGEREQUEST']._serialized_end=105
  _globals['_CLASSIFICATIONRESPONSE']._serialized_start=107
  _globals['_CLASSIFICATIONRESPONSE']._serialized_end=147
  _globals['_HEALTHCHECKREQUEST']._serialized_start=149
  _globals['_HEALTHCHECKREQUEST']._serialized_end=169
  _globals['_HEALTHCHECKRESPONSE']._serialized_start=171
  _globals['_HEALTHCHECKRESPONSE']._serialized_end=208
  _globals['_IMAGECLASSIFICATION']._serialized_start=211
  _globals['_IMAGECLASSIFICATION']._serialized_end=431
# @@protoc_insertion_point(module_scope)
